### ISSUE TITLE
Remove GDW directory after moving anything you want to keep to a new location

### ISSUE THREAD

**Issue by jelkner** [AidanLahlou/website#8]
Your [gdw](https://aidanlahlou.github.io/website/gdw/) directory now mostly has things from your earliest days learning HTML.  It would be better for your portfolio to remove it.  You may want to keep some things, like [some pictures I took](https://aidanlahlou.github.io/website/gdw/gallery2.html) before removing everything else.

**Comment by AidanLahlou** [comment]
will do jeff
